### ISSUE TITLE
Unable to run XS2A connector with Ledgers inside the docker container

### ISSUE THREAD

**Issue by f00bar** [adorsys/xs2a-connector-examples#4]
Hello,

I'm trying to load the XS2A connector with Ledgers inside the docker container as per the instructions listed here:https://github.com/adorsys/xs2a-connector-examples/blob/develop/GETTING_STARTED.md#xs2a-connector-with-ledgers-inside-the-docker-container

But my docker-compose command fails as listed below:

Step 6/9 : WORKDIR /opt/ledgers
 ---> Running in 773595fbd572
Removing intermediate container 773595fbd572
 ---> 10601792c9ee
Step 7/9 : COPY ./ledgers-app/target/ledgers-app.jar /opt/ledgers/ledgers-app.jar
ERROR: Service 'ledgers' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder988814120/ledgers-app/target/ledgers-app.jar: no such file or directory

Any ideas on how to resolve that ?

Thanks!

**Comment by DmitryMishchuk** [comment]
Hi,
Our suggestion would be to completely remove all containers/volumes/images from previous installations and try running docker-compose up on clean docker with no extra images running in background.

This can help you to clean your docker of volumes that are not bound to any image anymore:
`docker volume rm $(docker volume ls -q)`

**Comment by f00bar** [comment]
@DmitryMishchuk great - that solved the issue for me. Thanks!
